# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: f070355b525545353fb2e380ba2adbd8c7aeae874adaf360fbfda960c82ff0da911b9f4732fa4dce79c93838cce160fb8154a766d8e7e1fec40543436f0af519

test:
  secret_key_base: 8ad8c21460c33deec2e25a30264152c6365651a3162c077f41f328966af84245306276f5852b51aca4fc175f3ccf39aa578472c8aea868950c1c488491c0932a

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
